### ISSUE TITLE
Compilation errors using Visual Studio 2010

### ISSUE THREAD

**Issue by gkv311** [vslavik/winsparkle#102]
There are two compiler errors occurred when building current master of winsparkle using Visual Studio 2010:

1) Missing .po files (translation files).
For some reason commit f347dd48ff66bc0273b369ce0fbae79e15ec924c adds target for building .po files from .mo files only to VS2013 project file:
~~~~
+ <ItemGroup>
+ <None Include="WinSparkle.Targets">
+ <SubType>Designer</SubType>
+ </None>
+ </ItemGroup>
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
- <ImportGroup Label="ExtensionTargets" />
+ <ImportGroup Label="ExtensionTargets">
+ <Import Project="WinSparkle.targets" />
+ </ImportGroup>
~~~~
I have added the same target to VS2010 project file and it works fine.

2) C compiler of VS2010 is unable to compiler the line 1702 in file 3rdparty/expat/lib/xmlparse.c (function XML_GetBuffer):
~~~~
  if (len > bufferLim - bufferEnd) {
    int neededSize = len + (int)(bufferEnd - bufferPtr);
    if (neededSize < 0) {
      errorCode = XML_ERROR_NO_MEMORY;
      return NULL;
    }
#ifdef XML_CONTEXT_BYTES
    int keep = (int)(bufferPtr - buffer); //< compiler error at this line
~~~~
I have moved declaration of variable **keep** to the beginning of the block (requirement of old C standard) to be able compiling this file.

**Comment by vslavik** [comment]
> I have added 
…
> I have moved

So where’s the pull request? That would take much less effort on your end, and would be much more useful, than this issue. If you care about support for this 6 years old compiler, please help supporting it.

**Comment by gkv311** [comment]
Please see pull request:
https://github.com/vslavik/winsparkle/pull/103

**Comment by vslavik** [comment]
Closing in favour of (hopefully updated for git guidelines) #103.
