### ISSUE TITLE
Multiple versions in appcast and just one NotifyUpdateAvailable call

### ISSUE THREAD

**Issue by gaminn** [vslavik/winsparkle#107]
Hi,
I created appcast with multiple versions of my program (there are two item tags specifying 0.0.1 and 0.0.2 versions are available):

`<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
   <channel>
      <title>MyApp</title>
      <link>http://localhost/WinSparkle/appcast.xml</link>
      <description>MyApp</description>
      <language>en</language>
            <item>
         <title>MyApp 0.0.2</title>
         <sparkle:releaseNotesLink>https://winsparkle.org/example/relnotes.html</sparkle:releaseNotesLink>
         <pubDate>Tue, 16 Sep 2012 18:11:12 +0200</pubDate>
         <enclosure type="application/octet-stream" sparkle:installerArguments="/SILENT /SP-" sparkle:version="0.0.2" url="http://localhost/WinSparkle/0.0.2.exe"/>
      </item>
      <item>
         <title>MyApp 0.0.1</title>
         <sparkle:releaseNotesLink>https://winsparkle.org/example/relnotes.html</sparkle:releaseNotesLink>
         <pubDate>Tue, 15 Sep 2012 18:11:12 +0200</pubDate>
         <enclosure type="application/octet-stream" sparkle:installerArguments="/SILENT /SP-" sparkle:version="0.0.1" url="http://localhost/WinSparkle/0.0.1.exe"/>
      </item>
   </channel>
</rss>`

However, I get just one call of UI:NotifyUpdateAvailable and the info parameter is holding 0.0.2 version. How can I receive both 0.0.1 and 0.0.2 versions?

I have installed version 0.0.0 of MyApp. I reimplemeted ui.cpp (all methods are dummy).

**Comment by vslavik** [comment]
WinSparkle, *by design*, reports the latest version available — because it makes absolutely no sense to offer a obselete version to the user.

If you still believe there's some bug, kindly describe what it is, in detail, and provide reproducible test case. See also http://www.chiark.greenend.org.uk/~sgtatham/bugs.html.
