### ISSUE TITLE
Cancelling update during download when internet connection is lost freezes UI

### ISSUE THREAD

**Issue by gaminn** [vslavik/winsparkle#108]
Tried with:
WinSParkle-2013.sln, project example_psdk on Windows 10

When internet connection is lost in the middle of download of the update and user cancels download then the GUI completely freezes.

Also no error is displayed to the user that the internet connection has been lost.

**Comment by vslavik** [comment]
Confirmed (with the caveat that the application itself is fine, but WinSparkle is very much not). The fix is a little bit involved, so please bear with me.
