### ISSUE TITLE
Crash when attempting to download update multiple times

### ISSUE THREAD

**Issue by jaredburkeen** [vslavik/winsparkle#117]
Steps to reproduce:
Check for an update and download the update, but do not install it.
Then check for the update again, the next time you try to download the update the application will crash.

This issue appears to have been introduced with the commit to use WinInet asynchronously.

I reproduced this issue with my own application and also with Poedit (using my compiled Winsparkle.dll of the latest master).

![windows 10 dev-2016-10-07-10-36-09](https://cloud.githubusercontent.com/assets/1682254/19239233/168e2ad2-8ed3-11e6-9591-c6da459218ef.png)

**Comment by vslavik** [comment]
I can’t reproduce it with your instructions, but there’s a (now) obvious race condition related to `conn`. Thanks!

**Comment by vslavik** [comment]
Since I can’t reproduce this, testing would be appreciated. I think I understand what was the cause, but you know how it is...

**Comment by jaredburkeen** [comment]
Yes, I understand. I run into not the inability to reproduce issues constantly.
I tested your fix and it resolved the crash for me. Thank you!
