### ISSUE TITLE
build error no MSB3073

### ISSUE THREAD

**Issue by MonkeyHan** [vslavik/winsparkle#118]
Hello

D:\OpenSource\back\WinSparkle-0.5.2-src\WinSparkle.targets(19,5): error MSB3073: 命令“"D:\OpenSource\back\WinSparkle-0.5.2-src\\packages\Gettext.Tools.0.19.7.002\tools\bin\"msgfmt.exe -c -o "translations\ar.mo" translations\ar.po”已退出，代码为 3。
1>

**Comment by vslavik** [comment]
Sigh.

**Comment by MonkeyHan** [comment]
The problem has been solved. Thank you!

**Comment by vslavik** [comment]
Yes, I see that. Please kindly change your habits and investigate *first* and only *then* file issues, *if* you’re unable to solve the problem, not the other way around. Polluting issue trackers and wasting others’ time like this is a rude and inconsiderate thing to do.

Also worth noting that posting output, with no explanation whatsoever, in Chinese, is not as useful as you think it is.

**Comment by MonkeyHan** [comment]
So sorry about that.
And thank you for your suggestion.
