### ISSUE TITLE
How to config winsparkle to check for update on startup?

### ISSUE THREAD

**Issue by sinall** [vslavik/winsparkle#121]
I need my program check for update every time when it startup.

In the header file it says:

> If WinSparkle is configured to check for updates on startup

But I didn't find the configuration for this. Could someone point out the function? Thanks.

Here's the code:

```
win_sparkle_set_appcast_url("...");
win_sparkle_set_automatic_check_for_updates(1);
win_sparkle_set_lang("zh-CN");
win_sparkle_init();
```

Is the 'win_sparkle_set_automatic_check_for_updates' also affected by the check interval or 'skip this version' button? I maybe have had clicked the button.

**Comment by vslavik** [comment]
Read the docs. Check the example (that’s right, there’s a *freaking example* that you can look at and run to see how it works!). Please don’t use the *bug tracker* for idle *questions*.
