### ISSUE TITLE
win_sparkle_update_cancelled_callback not called when closing installation window

### ISSUE THREAD

**Issue by glaubitz** [vslavik/winsparkle#127]
Currently, the win_sparkle_update_cancelled_callback callback function is called when the user click "Skip Update", "Remind Me Later" or when the "Cancel" button is clicked when the update is being downloaded.

However, win_sparkle_update_cancelled_callback is not called when the user just closes the "Ready to install" dialog instead of clicking "Install updates" although this effectively cancels the update process as well.

**Comment by vslavik** [comment]
Please submit a PR with the fix, then. As one of the *very* few users of this callback, you’re in the best position to do it and contribute back.

**Comment by buwen-D** [comment]
@glaubitz Hello, I am also experiencing this problem now, and I need something to be done when the user closes the "Ready to install" dialog box, may I know how you fix it?
