### ISSUE TITLE
Update check interval restriction to a minimun time of 1 hour is an unnecessary limitation

### ISSUE THREAD

**Issue by GitHubschrauber** [vslavik/winsparkle#128]
There is the following restriction for setting the update check interval:
WIN_SPARKLE_API void __cdecl win_sparkle_set_update_check_interval(int interval);
@param  interval The interval in seconds between checks for updates.
                     The minimum update interval is 3600 seconds (1 hour).

This causes problems when testing the software. It's reasonable to make several test runs before one hour elapses.
In the case of a menu item "Check for Updates" a check for updates should usually be performed because the user wishes to do such a check.

My suggestion is to skip this restriction and to allow update intervals of 0 seconds but to keep the default value.

**Comment by vslavik** [comment]
This is not going to change. Please don’t assume others’ incompetence as the first explanation — there are actual reasons for this, it’s a protection against shooting yourself in the foot and flooding an update server with requests. Sparkle does the same thing, and reasonably so.

Your claim that this affects manual updates is false, of course, and would have taken less than a minute to check for yourself.

Your claim that this causes problems with testing is also false: nothing prevents you from (trivially!) faking the last update time or removing the relevant registry value altogether.

**Comment by GitHubschrauber** [comment]
Thank you for your hint with the manual updates. I spent a lot more time than one minute but sometimes people do make errors or remember things wrongly so as I did and then they don't find a solution although actually it should have been quite straigthforward.
