### ISSUE TITLE
Release notes html and setup file is not downloading updated version

### ISSUE THREAD

**Issue by jrpatil77** [vslavik/winsparkle#130]
Hi,

In my scenario, Suppose  I have initial version installed on my machine as 1.0.0. I kept my setup file, appcast file and release note html file on Server location for version 1.0.1. When winsparkle pops for new update, i downloaded it but not installed it. Then suppose new version  1.0.2 kept on server  with its release note. When i again try to launch app, it show me 1.0.2 is available but not downloading 1.0.2 setup file and release note instead it shows 1.0.1 release notes and setup file

**Comment by jrpatil77** [comment]
I guess it somehow caching setup file and release notes file. Can i configure it to no cache

**Comment by vslavik** [comment]
You are *way* too ready to blame everybody but yourself. Please follow the time-tested engineering principle of blaming your own stuff first and only filing bugs with 3rd parties once you *ruled out problems on your end*.

It stands to reason that a problem like this would be noticed many times over already -- yet it wasn't. The simplest explanation for that curious fact is that WinSparkle is in fact following your server's instructions and your server is forcing caching. A standard browser is used to show release notes. It behaves as any other browser in this regard, including following *server's instructions* on caching.

If you have reason to believe there is something wrong in WinSparkle, *after having investigated it and ruled out causes on your end*, amend this issue with [proper bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) that actually includes steps to reproduce and all information and/or code necessary to do so.
