### ISSUE TITLE
Error getting temp filename

### ISSUE THREAD

**Issue by lehne** [vslavik/winsparkle#131]
I am using WinSparkle 0.5.3 and when I try to download an update I get an error. I think the error is because of an invalid filename for the temp file name (similar to  #109) I am using WinSparkle in a C# app (probably irrelevant) and am downloading the updates via a redirect (similar to hockeyapp). My url is something like files.myorg.com/myfile.msi which then is redirected to an Azure Blob with a Shared Access Signature good for a certain amount of time. This means that the url is more like blobs.azure.net/myfile.msi?pv=fd&sdfd&sfdd&etc

The app feed rss downloads fine through this method (as does the file) but when trying to save it to the file system, Sparkle errors out (I think because the file is invalid). In the debugger, I noticed that this code returns the filename with the Shared Access Signature still on it. 

```
std::wstring GetURLFileName(const char *url)
{
    const char *lastSlash = strrchr(url, '/');
    const std::string fn(lastSlash ? lastSlash + 1 : url);
    return AnsiToWide(fn);
}
```

Then, the code errors out in this block:
```
virtual void SetFilename(const std::wstring& filename)
    {
        if ( m_file )
            throw std::runtime_error("Update file already set");

        m_path = m_dir + L"\\" + filename;
        m_file = _wfopen(m_path.c_str(), L"wb");
        if ( !m_file )
            throw std::runtime_error("Cannot save update file");
    }
```

**Comment by vslavik** [comment]
You're being very vague to the point of this issue being incomprehensible :( Surely as a developer you must understand that details matter in a bug report, that it must be specific, detailed, accurate and above all, *reproducible*, and that words like "like" have little place in it.

Please provide a reproduction case. You don't even say *what* the error is. You didn't provide the feed. You claim that it "errors out" in a specific place, yet don't say how and don't provide readily available information from that place such as the value of `m_path`, despite running it under a debugger. I don't know what you mean by SAS here or why you think the above referenced bug has any relationship. Can you please explain in more detail and sticking to just the facts ([this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) might be helpful)?

I can't fix what I can't see, simple as that...

**Comment by lehne** [comment]
Hi Václav,
Sorry about my vague bug report. I thought I had already found the issue and was trying to explain it to you rather than have you diagnose it. I can do a pull request if you prefer, but I haven't used much C++ lately. As far as more details, here are samples of the signatures used:
Sparkle has no problem downloading the .rss. In this case, Sparkle correctly uses the original filename before redirect (appdescriptor.rss):
`appdescriptor.rss?sv=2015-12-11&sr=b&sig=d%2B0%2BzLVcCgA2S6wiYmY53rZAzUEdeWQyC5K8cz09e60%3D&se=2017-03-02T22%3A18%3A20Z&sp=r&ext=.rss`

However, the file that is referenced in the rss, "Installer.msi", has the entire redirected url chosen as the temp filename:
`Installer.msi?sv=2015-12-11&sr=b&sig=pQCIiUtQwihnuN4JaFg2ofF2ypQM0o%2BByej75cVMqy0%3D&se=2017-03-02T22%3A28%3A01Z&sp=r&ext=.msi`
Does not work. In the Sparkle code, it tries to use this entire string as the filename:
`m_path = m_dir + L"\\" + filename;`
The error is thrown here:
```
if ( !m_file )
            throw std::runtime_error("Cannot save update file");
```
Checking for a '?' character in the filename and excluding the question mark and all of the characters after it should fix the issue. A '?' is a reserved character in Windows and cannot be in filenames. Thanks!

**Comment by vslavik** [comment]
Again, can you *please* provide *reproduction steps* — such as the actual appcast feed? It's useful for verifying the fix you know...

**Comment by lehne** [comment]
I just did a pull request to fix it so that the function does not return invalid windows filenames. However, I also changed my server so that it returns a Content-Disposition header with the filename, which Sparkle already accounts for. Once I did that, the problem was resolved for me and Sparkle could download the update.

**Comment by vslavik** [comment]
(Reopening: no fix committed yet.)
