### ISSUE TITLE
automatic update interval sleepTime is seconds or millisecond?

### ISSUE THREAD

**Issue by ioozhuangzi** [vslavik/winsparkle#141]
automatic update interval is seconds. but sleepTime is millisecond?
In updatechecker.cpp ,UpdateChecker::Run():
unsigned sleepTime = 60 * 60 * 1000; // 60mins    // milliseconds ?
...
if (checkUpdates)
        {
            const time_t currentTime = time(NULL);
            time_t lastCheck = currentTime;
            Settings::ReadConfigValue("LastCheckTime", lastCheck);

            // Only check for updates in reasonable intervals:
            const int interval = win_sparkle_get_update_check_interval();
            time_t nextCheck = lastCheck + interval;
            if (currentTime >= nextCheck)
            {
                PerformUpdateCheck();
                sleepTime = interval; //millisecond = second ?
            }
            else
            {
                sleepTime = unsigned(nextCheck - currentTime);//millisecond = second ?
            }
        }

        m_terminateEvent.WaitUntilSignaled(sleepTime);//milliseconds??

**Comment by vslavik** [comment]
Took me a while to parse what you mean, but yes, you're right, there is a mismatch. Thanks!

**Comment by ioozhuangzi** [comment]
@vslavik Not at all~I can‘t describe it clearly because my English is poor.^_^
