### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by AdamMoschnitzka** [vslavik/winsparkle#143]
Hello,

we are using the winsparkle in our program and we noticed a mistake in the hungarian translation. Pls, fix it in the next release if you can. (If the application is up to date.) Here is how we solved it:
[hu.txt](https://github.com/vslavik/winsparkle/files/1139236/hu.txt)

**Comment by vslavik** [comment]
Yeah, I'm not going to look through that dump of text to find some minuscule difference you don't even bother to spell out.

The *least* you could in return for being able to use WinSparkle is to [read the README](https://github.com/vslavik/winsparkle/blob/master/translations/README) and follow the instructions there. It's easy.
