### ISSUE TITLE
win_sparkle_init doesn't trigger update check on first startup (regression)

### ISSUE THREAD

**Issue by solusipse** [vslavik/winsparkle#144]
**Description:**
In `0.5.3`, calling `win_sparkle_init()` results in performing a silent check. With `0.5.4` this doesn't happen anymore - no window is displayed apart from settings used, no callback functions are called.

**Reproducing:**
Master and latest release (`0.5.4`) are affected. `0.5.3` seems to work just fine. Can be reproduced with both examples provided in the repository.

Had no time to check which commit breaks it, sorry. Can do that tomorrow (maybe even provide a fix).

**Comment by vslavik** [comment]
> Had no time to check which commit breaks it, sorry. Can do that tomorrow (maybe even provide a fix).

Please do, I'm on vacation and can't. Prime candidates are cb4b0fd7c788bed0b2e94eb19832e05ab32a2916 (#126), f0ddddc274cf94fcfaa0bd4ee7af094fc12e4515 and 2b326cbbcccb940791a617a68d19674542cd0c8c (#141). I'm petty sure I tested it, so my bet would be on the last one.

**Comment by vslavik** [comment]
I just verified that checking for updates does in fact work correctly.

If you believe otherwise, please provide [detailed instructions](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) on how to reproduce it in the example_psdk sample included with WinSparkle, including information about your OS, relevant registry values (such as `LastCheckTime`) and times of invoking any operations necessary to reproduce.

**Comment by cloudshao** [comment]
I ran into this issue as well. Repro:
1. Delete the LastCheckTime registry value
2. Run example_psdk, don't press the manual check button

Result:
- No update dialog appears

Expected:
- Update check happens and update dialog appears

Please see my attempted fix in PR #146

**Comment by vslavik** [comment]
Ah, on the *first ever* check — OP's use of "anymore" threw me off and I tested only with pre-existing `LastCheckTime` records (and the subsequent lack of communication despite promises made it look like your usual PEBKAC). 

Thanks a lot for looking into it in more detail, pointing out the broken case *and* providing a PR — I fully agree with your analysis in #146.

**Comment by cloudshao** [comment]
Cheers! Thanks for all your hard work on winsparkle. 😄

**Comment by vslavik** [comment]
Just uploaded v0.5.5 with @cloudshao fix.

**Comment by solusipse** [comment]
Very sorry for my delayed response. When I meant anymore, I meant for the latest version - sorry for not being precise enough. Thank you for fixing that!
