### ISSUE TITLE
Clarify .net code sample

### ISSUE THREAD

**Issue by glen-nicol** [vslavik/winsparkle#148]
I think the [.net sample](https://github.com/vslavik/winsparkle/wiki/Basic-Setup#user-content-2-create-a-wrapper-for-the-winsparkle-methods-you-are-going-to-call) could be updated since it confuses the two styles of manual vs automatic checks. 

It would be clearer if the following line:
```chsarp
WinSparkle.win_sparkle_check_update_with_ui(); 
```
was moved into something like this:

```csharp
public void Form1_button1_click(object sender, EventArgs e)
{
    //invoke manual update check from button or menu click.
    WinSparkle.win_sparkle_check_update_with_ui();
}
```

Then to reinforce that init starts the automatic updating a comment could be added that says as much. The page does say that [init does the automatic updates](https://github.com/vslavik/winsparkle/wiki/Basic-Setup#3-initialize-winsparkle) but I also think it is reasonable to assume devs are busy and skip to the .net section without reading the C++ section. I definitely did at first.

It is also worth mentioning that I only found this out because I observed spotty behavior with the without_ui variant being called immediately after init. Reading the sample and copying verbatim seemed like a logical and legit use.

**Comment by vslavik** [comment]
> It would be clearer

Please make the changes, then — it's user-editable wiki. Thanks!

**Comment by glen-nicol** [comment]
Oh so it is. I've never editted a wiki on github before so I didn't know where to look. Done.

**Comment by vslavik** [comment]
Thanks!
