### ISSUE TITLE
check_for_updates_without_ui() no longer works

### ISSUE THREAD

**Issue by dyer234** [vslavik/winsparkle#154]
I have something odd happening here. I reproduced it on two machines with visual studio 2015 running on Windows 10. I was hoping someone could try and reproduce it as well. If its a legitimate bug I might be able to work on it.

## Steps to reproduce:

1. Line 69 app_psdk.c Change the function being used from check_for_updates_with_ui() to check_for_updates_without_ui()
2. Compile, run, click the button entitled "Check for Updates Manually"

## Expected result:
There is no graphical indication of update check but the a notification that appears showing an update is available

## Actual Result:
After clicking on the button, the user is not presented with an update

## Findings:
It appears that this was broken in commit cb4b0fd. The previous commit 57aef82 does not have the issue and check_for_updates_without_ui() works as expected.

**Comment by vslavik** [comment]
You're right :( Fixed in 55fb7b51fde7afa7fdbbc7aaf86087784f68d78b.

**Comment by codecat** [comment]
Just ran into this on the latest binary release! Will you be updating that, or should I just build it myself?
