### ISSUE TITLE
Multiple check for updates calls when existing window is open does not load release notes

### ISSUE THREAD

**Issue by johnmurphy01** [vslavik/winsparkle#155]
When a check for updates dialog UI is already open and subsequent check for updates occur while the dialog UI is _still_ open results in the release notes text not loading. This is in the case that release notes are loaded from the `<description>` tag.

Steps to reproduce:
- Launch application
- Invoke WinSparkle so that a new update UI is present
- Manually check for updates while the UI is open
Observe that the release notes text area has no content.

First update check:
![image](https://user-images.githubusercontent.com/2939548/33849094-359239b2-de75-11e7-8233-093438691764.png)

Next update check with the WinSparkle window still open:
![image](https://user-images.githubusercontent.com/2939548/33849109-3f510500-de75-11e7-9980-cb530bb9525f.png)

I believe this is due to the web browser already being loaded and so there is some initialization that needs to take place but is getting skipped. I will make my proposed modification and submit a PR.

**Comment by johnmurphy01** [comment]
https://github.com/vslavik/winsparkle/pull/156

Thanks!

**Comment by danielgary** [comment]
This appears to be a problem with your secret application code.  Something YOU are doing is causing the problem, not WinSparkle.

**Comment by vslavik** [comment]
"Backporting" important update from #156 (feel free to create PRs right away without corresponding issue, BTW):
> Added Note: This issue does appear to only affect release notes that are loaded using the description tag. Loading release notes using a url does not appear to have this issue.
