### ISSUE TITLE
My project fails to build, missing assemblies

### ISSUE THREAD

**Issue by tmcmanameyunl** [vslavik/winsparkle#158]
I building a project with msbuild on win server 2012 R2.  I'm getting the following:
_C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1098,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found._
When I remove winsparkle from my project this error goes away.  I've tried rebuilding winsparkle for .net 4.6.2 and still didn't work.  Is it possible there is some header ws is including that's causing this?  Any recommendations?

Thanks.

**Comment by vslavik** [comment]
>  Is it possible there is some header ws is including that's causing this? 

Self-evidently no: WinSparkle is a native win32 DLL. It cannot possibly be built "for .NET 4.6.2" and it doesn't reference or create any "assemblies", so such an error couldn't possibly be related to it. Unless, of course, you did some changes you didn't see fit to disclose.
