### ISSUE TITLE
A reference to WinSparkle.dll could not be added

### ISSUE THREAD

**Issue by tjosten** [vslavik/winsparkle#167]
Hi,

I am trying to integrate WinSparkle into my WinForms C# application, am however unable to add a Reference to the WinSparkle.dll file in the latest release:

![screenshot-2018-02-24-18-37-22](https://user-images.githubusercontent.com/807586/36633229-ec6ee3a4-1991-11e8-9a5f-070378710e64.png)

I am relatively new to C# and Visual Studio so I simply might be doing something wrong. Can you help, please?

Thanks and best wishes,
Timo

**Comment by vslavik** [comment]
Read the wiki — and MSVS docs. You are confused about the difference between assemblies and native DLLs.
