### ISSUE TITLE
Error Signing Data

### ISSUE THREAD

**Issue by wjkhappy14** [vslavik/winsparkle#175]
\bin\sign_update.bat  NetSparkleTestAppWPF.exe   dsa_priv.pem                  
Error Signing Data                                                                                                
**17800:error:0606B06E:digital envelope routines:EVP_SignFinal:wrong public key type:.\crypto\evp\p_sign.c:99:**

**Comment by wjkhappy14** [comment]
use bin/generate_keys.bat  to get the pri/pub key

**Comment by Youw** [comment]
> What version of openssl you're using? Have you compiled it yourself, or download precompiled binaries?

**Comment by quantonganh** [comment]
> * What version of openssl you're using? Have you compiled it yourself, or download precompiled binaries?

0.9.8h-1, downloaded from here: 
http://downloads.sourceforge.net/gnuwin32/openssl-0.9.8h-1-setup.exe

**Comment by quantonganh** [comment]
I tried openssl version from [Cygwin](https://www.cygwin.com) and it's ok now.

**Comment by vslavik** [comment]
Closing as user error (using ancient OpenSSL versions instead of the one readme points to), then.
