### ISSUE TITLE
Provide some ways to override registry functions

### ISSUE THREAD

**Issue by BSG-75** [vslavik/winsparkle#178]
WinSparkle currently uses Windows Registry to store the majority of settings, but sometimes I need to manage settings by myself, and in this situation, it would be really nice if we could override the functions
`RegistryRead`, `RegistryWrite` and `RegistryDelete`.

For example, WinSparkle could have 3 function pointers, which point to the three functions above by default, but users can choose to override the original functions by setting callbacks.

**Comment by vslavik** [comment]
Make a PR instead of submitting “it would be really nice” nuisance issues.
