### ISSUE TITLE
Are delta updates possible ?

### ISSUE THREAD

**Issue by pedroosorio** [vslavik/winsparkle#180]
Hey @vslavik !

Is Win Sparkle supporting delta updates ???

Thanks !

**Comment by Youw** [comment]
https://github.com/vslavik/winsparkle/issues/169

**Comment by vslavik** [comment]
Yeah, please show the courtesy of reading docs and using search before creating and issue.

**Comment by pedroosorio** [comment]
@vslavik i looked in the readme and the docs and i can't find references to delta updates, but my bad! 

Thanks for the help !
