### ISSUE TITLE
Application freezes in deadlock if wxWidgets failed to initialize

### ISSUE THREAD

**Issue by polosha** [vslavik/winsparkle#182]
In [ui.cpp](../blob/master/src/ui.cpp)
On line 1451 current thread (gui thread) waits until UIThreadAccess::ms_uiThread will signal an event
On line 1495 (executed in ms_uiThread) in case of wxInitializer failure it returns, thus never signalling an event so UI thread waits infinitely

**Comment by vslavik** [comment]
Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and provide actual understandable description, with reproduction steps. Do not reference specific lines, they are ever-changing. If you are sure that there's a bug and what it is (as you seem to), please do one better and provide a PR with the fix.
