### ISSUE TITLE
Problem with generate_keys.bat

### ISSUE THREAD

**Issue by ZhuShentian** [vslavik/winsparkle#185]
by running the generate_keys.bat, i got the error msg:
gendsa: Use -help for summary.
read DSA key
Can't open dsa_priv.pem for reading, No such file or directory
7572:error:02001002:system library:fopen:No such file or directory:crypto\bio\bss_file.c:72:fopen('dsa_priv.pem','r')
7572:error:2006D080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:79:
unable to load Private Key
unable to load Key
Failed to create "dsa_priv.pem"!

after modifying the script in generate_keys.bat, i got the priv and pub pem files successfully:
openssl gendsa  dsaparam.pem -out dsa_priv.pem
==> openssl gendsa -out dsa_priv.pem dsaparam.pem 

P.S. i am using Win64OpenSSL_Light-1_1_1a.

**Comment by vslavik** [comment]
If you know what needs changing, please do the small extra step of contributing a PR that makes the change, instead of describing what should be done — the latter is not entirely clear, a patch would speak for itself.

Thanks!

**Comment by Youw** [comment]
Hmm, we haven't been testing OpenSSL 1.1.x, only 1.0.2.
It looks like that version requires passing all named ("-") parameters before unnamed ones.

PR would be great.

**Comment by z-pc** [comment]
Try copy openssl.exe in directory setup to same directory with generate_keys.bat. Try again
