### ISSUE TITLE
fatal error: QResource: No such file or directory

### ISSUE THREAD

**Issue by quantonganh** [vslavik/winsparkle#188]
I'm using WinSparkle in Qt ([binding for Go](https://github.com/therecipe/qt)) app follow [your example](https://github.com/vslavik/winsparkle/tree/master/examples/qt).

To set DSA public key from Qt resource, I tried: https://github.com/vslavik/winsparkle/blob/master/examples/qt/mainwindow.cpp#L48

My `main_windows.go`:

```
package main

/*
#cgo CPPFLAGS: -I ${SRCDIR}/WinSparkle/include
#cgo LDFLAGS: -L${SRCDIR}/WinSparkle/Release -lWinSparkle

#include <QResource>

#include "winsparkle.h"

void initWinSparkle()
{
    win_sparkle_set_dsa_pub_pem(reinterpret_cast<const char *>(QResource(":/WinSparkle/dsa_pub.pem").data()));
    win_sparkle_init();
}
*/
import "C"

func xx() {
	C.initWinSparkle()
}
```

but I got the below error:

>2018/12/20 08:29:15 .\main_windows.go:10:21: fatal error: QResource: No such file or directory

How can I fix it?

**Comment by Youw** [comment]
I bet you didn't add [Qt resource](http://doc.qt.io/qt-5/resources.html) to your project.

Check out [sample resource](https://github.com/vslavik/winsparkle/blob/master/examples/qt/resources.qrc), and the way Qt [usually does its integration](https://github.com/vslavik/winsparkle/blob/master/examples/qt/QtExampleApp.pro#L34).

Also note, this is not a support forum. If you try bundled example as is - it is working.
What you're trying to do (load public key from Qt resource using Go-to-Qt binding) - has nothing to do with WinSparkle.

Please use Stackoverflow to issue such questions. This place - is for WinSparkle bugs.
