### ISSUE TITLE
Registry functions are atomic => why need to guard DoWriteConfigValue/DoReadConfigValue?

### ISSUE THREAD

**Issue by ehaerim** [vslavik/winsparkle#192]
// Critical section to guard DoWriteConfigValue/DoReadConfigValue.
CriticalSection g_csConfigValues;

void Settings::DoWriteConfigValue(const char *name, const wchar_t *value)
{
    CriticalSectionLocker lock(g_csConfigValues);
    RegistryWrite(name, value);
}
std::wstring Settings::DoReadConfigValue(const char *name)
{
    CriticalSectionLocker lock(g_csConfigValues);
    wchar_t buf[512];
    if ( RegistryRead(name, buf, sizeof(buf)) )
        return buf;
    else
        return std::wstring();
}

void Settings::DeleteConfigValue(const char *name)
{
    CriticalSectionLocker lock(g_csConfigValues);
    RegistryDelete(name);
}

I am not sure why we need to guard the above functions.
Could someone explain what would go wrong without guarding?

thx

**Comment by vslavik** [comment]
> Registry functions are atomic

But a sequence of them, with additional logic, isn't. 

P.S. Still waiting for your clarification on the other issue you filed.

**Comment by ehaerim** [comment]
> > Registry functions are atomic
> 
> But a sequence of them, with additional logic, isn't.
> 
>> I don't understand.  Please can you explain why sequence needs synchronization?
