### ISSUE TITLE
Setting HTTP_PROTOCOL_FLAG_HTTP2 means what?

### ISSUE THREAD

**Issue by ehaerim** [vslavik/winsparkle#193]
void DownloadFile(const std::string& url, IDownloadSink *sink, Thread *onThread, int flags)
{
...
    DWORD dwOption = **HTTP_PROTOCOL_FLAG_HTTP2**; // a custom option, isn't it?
    BOOL bRet = InternetSetOptionW(inet, INTERNET_OPTION_ENABLE_HTTP_PROTOCOL, &dwOption, sizeof(dwOption)); // **bRet is FALSE, and GetLastError is 183**
...
}
Please explain what is the above custom option for and why I got error 183?
Thx

**Comment by vslavik** [comment]
This is a *bug tracker* - a place for reporting bugs. This is not an idle talk forum, this is not a university, and I'm not your teacher or personal googling assistant.

Your question is trivially answerable with google. Your previous similar non-bug issue was CS 101 question.

Please refrain from this inappropriate behavior in the future or I will be forced to block you.
