### ISSUE TITLE
Example uses insecure sha1 for signing updates

### ISSUE THREAD

**Issue by jlobello** [vslavik/winsparkle#194]
bin\sign_update.bat is using sha1 for hashes.  As I'm sure you know, sha1 is being phased out. Is it ok to use sh256?  If so, you should update the examples.

**Comment by vslavik** [comment]
> insecure sha1

Let's avoid [hysterical](https://wccftech.com/google-cracked-sha1/) proclamations, shall we. As I'm sure *you* know, there's a very wide gap between theoretical insecurity and practical attacks on arbitrary files. DSA, particularly with short keys, is considered insecure too.

You can't just change signature scheme to use a different hash and expect it to magically continue to work. You can toss compatibility out of the window either. So thanks for telling us what we "should" do, but you are mistaken.

Migration to Sparkle-compatible signature scheme using ed25519 and sha512 is part of #187.
