### ISSUE TITLE
JoinAndDelete not found?

### ISSUE THREAD

**Issue by ehaerim** [vslavik/winsparkle#195]
/**
    Lightweight thread class.

    It's a base class; derived class must implement at least Run().

    Create the thread on heap, then call Start() on it. If the thread is joinable
    (see IsJoinable()), then you must call **JoinAndDelete()** on it to destroy it.
    Otherwise, it self-destructs.
 */

I don't see JoinAndDelete nowhere in the source.
Where is it?

**Comment by vslavik** [comment]
Thanks, fixed.

You have the class' declaration *right under* this comment.

It really doesn't take a genius to realize the method was renamed to `TerminateAndJoin` since the comment was written. (Or to be more constructive and start the conversation by submitting a PR correcting the evident typo.)

**Comment by ehaerim** [comment]
Why closed without any answer?

**Comment by vslavik** [comment]
The answer is right above your question, if only you have *read* it...
