### ISSUE TITLE
Version with .0 ending is preferred over the one with .1

### ISSUE THREAD

**Issue by kir-medvedev** [vslavik/winsparkle#199]
Hey guys,
I've caught a strange behavior of WinSparkle with .0 version suffix in the end.
The case is:
1. Set an application version by win_sparkle_set_app_details() call with .0 ending, for example "0.13.0".
2. Put an appcast.xml file on the server with versions 0.13.0, 0.13.1.
3. Initiate the update by win_sparkle_check_update_with_ui() call.

Observed: WinSparkle thinks that 0.13.0 version is the latest one and doesn't need to be updated.
If I remove the prefix .0 (till "0.13"), everything works well.

Can somebody else verify the issue exists not only in my setup?

I am using latest stable version 0.6.

UPDATE:
It looks like the case depends on version items positions in the appcast.xml feed.
If I place the 0.13.1 item before the 0.13 one, everything works well.

Is it expected behavior, that version item position in appcast matters?

**Comment by vslavik** [comment]
> Can somebody else verify the issue exists not only in my setup?

You can't reasonably ask volunteers to do that. Instead, try to minimize the issue and provide full reproduction steps within WinSparkle's examples. It's a win-win: either you identify issues on your end or understand the issue better to phrase it more accurately (both happened here) or you make it obvious it's an actual bug and dead-simple to reproduce. 

> UPDATE: It looks like the case depends on version items positions in the appcast.xml feed.

This being case in point.

WinSparkle [doesn't sort](https://github.com/vslavik/winsparkle/blob/0388af88deb6bf399d5ccebbfe8a63579ec4d2b2/src/appcast.cpp#L330) the appcast. As far as I can determine from the code, neither does Sparkle. If I'm wrong about Sparkle, I'm certainly open to patches changing the behavior.

Pragmatically speaking, though, using a sanely ordered feed seems simpler. RSS 2.0 spec doesn't mandate sort order, so an unordered feed isn't *de iure* wrong, but having the newest at the top is *de facto* standard. Again, from my reading of Sparkle's code, this is a spec-by-code requirement on appcast feeds too, but I may be misreading it.
