### ISSUE TITLE
How can I move APPCAST resouce

### ISSUE THREAD

**Issue by z-pc** [vslavik/winsparkle#200]
Hi @vslavik
My product can't set the static url of the app cast in resource file, because my server update address may changed. If change, I will notify to user about the app cast url. 
So, I want to my user can config the address by a text, xml file or registry.
Do you have any recommend for me to handle this problem ?

**Comment by vslavik** [comment]
See [the documentation](https://github.com/vslavik/winsparkle/blob/master/include/winsparkle.h#L160).
