### ISSUE TITLE
Installer Arguments (<sparkle:installerArguments>) probably ignored

### ISSUE THREAD

**Issue by spekdrum** [vslavik/winsparkle#201]
I've configured an enclosure to download a setup app made with InnoSetup. When I manually run this setup with the argument "/SILENT" it behaves as expected (in silent mode). But it doesn't work  when it's downloaded and executed through Winsparkle.

This is my appcast file:

`<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>Test</title>
        <description>Most recent updates to test</description>
        <language>en</language>
        <item>
            <title>Version 1.0.1</title>
            <sparkle:installerArguments>
                /SILENT
            </sparkle:installerArguments>
            <enclosure url="http://localhost:8090/updates/setup.exe"
                       sparkle:version="1.0.1"
                       length="0"
                       type="application/octet-stream" />
        </item>
    </channel>
</rss>`

I'm using it manually with this method: win_sparkle_check_update_with_ui_and_install(), but I tried the other manual methods with same result.

**Comment by Marginal** [comment]
sparkle:installerArguments goes within the "enclosure". So:
```xml
<enclosure url="http://localhost:8090/updates/setup.exe" sparkle:version="1.0.1" sparkle:installerArguments="/SILENT" length="0" type="application/octet-stream" />
```

**Comment by spekdrum** [comment]
It worked, thanks!!
