### ISSUE TITLE
Installer gets killed when application is quit/terminated.

### ISSUE THREAD

**Issue by tusharh** [vslavik/winsparkle#203]
I have integrated WinSparkle with QT. On finding an update & after clicking "install update", I get win_sparkle_set_shutdown_request_callback. In it on calling QApplication::quit/exit the installer launched also gets killed along with the main application. Is there anything that I'm missing? Thanks in advance.

**Comment by vslavik** [comment]
> Is there anything that I'm missing?

For starters, http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

Your assumption that this happens to everybody, with every kind of installer, with every piece of hosting software, and you therefore don't need to provide any details, is incorrect. I, for example, see no such issues with Inno Setup or MSI.

If the way you terminate the process and/or the mysterious installer you use is incompatible with the way WinSparkle works, your PR, or a detailed actionable description of the issue, would be most welcome and it could be fixed. As it is, I can't do much more than shrug helplessly give the lack of information.

**Comment by tusharh** [comment]
My bad for lack of information. I,m using -
WinSparkle - 0.6.0
QT - 5.9.4
& the installer is an .exe made with "nsis" installer script. 
Will try to modify my code to work. Will add PR with enhancements if it works out.

**Comment by vslavik** [comment]
> tusharh closed this 2 hours ago

A bit rude to close the issue without explanation after having asked us for help...

**Comment by tusharh** [comment]
Had checked out .msi & it worked fine. Nsis exe installer will need some research & if possible a PR. I'm trying to find a solution. Will move to msi build. So, to just decrease the open issues on your plate & correct my code to msi build marked it as closed. Thanks for suggesting msi.

**Comment by vslavik** [comment]
Thanks! If this meant general incompatibility with NSIS ,that would be worrying...

**Comment by Youw** [comment]
I have a (Qt) project that is using NSIS and WinSparkle with no issues, so I'd say "general incompatibility" shouldn't be the case. (At least I don't have any workarounds on that regard or on regard WinSparkle at all).

An important note: I don't set `win_sparkle_set_shutdown_request_callback` at all, and so far everything worked correctly.
