### ISSUE TITLE
[Question] How to unload winsparkle dll?

### ISSUE THREAD

**Issue by rkitover** [vslavik/winsparkle#208]
What we do is pack the dll as a resource and write it out to a temp file before using a wx api that uses `LoadLibrary()`.

Unfortunately I started getting an access denied error when closing the app when trying to delete this file.

Other than calling `win_sparkle_cleanup()` and then `FreeLibrary()` can anything be done to completely unload the DLL?

**Comment by vslavik** [comment]
Sorry, but this really is not an appropriate channel to ask for win32 programming education.

Whatever problem you're having has absolutely nothing to do with WinSparkle. You choose to jump through some crazy hops to accomplish what can be done sanely; you need to have sufficient knowledge of win32 to pull it off.
