### ISSUE TITLE
Cannot build as static link in an existing application

### ISSUE THREAD

**Issue by deanis74** [vslavik/winsparkle#211]
In `winsparkle.h` I have to change:
```
    #ifdef BUILDING_WIN_SPARKLE
        #define WIN_SPARKLE_API __declspec(dllexport)
    #else
        #define WIN_SPARKLE_API __declspec(dllexport)
    #endif
```

to:
```
    #else
        #define WIN_SPARKLE_API
    #endif
```

After that I can link statically.

**Comment by vslavik** [comment]
The MSVC solution doesn’t have any static target for a reason: it is not supported. WinSparkle is a DLL by design.

Filing an issue that you cannot do something that _you’re not meant to do_ is weird.

**Comment by deanis74** [comment]
In this case, you will probably want to remove this code and comment from `UI::Run()`:
```
    if ( !ms_hInstance )
    {
        // If DllMain() was not called, assume we're statically linked
        // and use the hInstance of the containing program.
        ms_hInstance = GetModuleHandle(NULL);
    }
```
