### ISSUE TITLE
[Question] Updating Microsoft docs for Sparkle usage

### ISSUE THREAD

**Issue by Deadpikle** [vslavik/winsparkle#213]
Hey!

I am the current maintainer of [NetSparkleUpdater](https://github.com/NetSparkleUpdater/NetSparkle), a C# version of the Sparkle library. We're nearing a 2.0 version (well, whenever I get around to finishing writing docs and stuff, but it seems fairly stable at this point). I would like to update the Microsoft Docs AppCenter page [here](https://docs.microsoft.com/en-us/appcenter/distribution/sparkleupdates) ([source here](https://github.com/MicrosoftDocs/appcenter-docs/blob/live/docs/distribution/sparkleupdates.md)) to provide people with knowledge of both the C++ and C# options. I am not wanting to force people to use "my" lib or anything, as I think there are use cases for both, so I'd like to see if we can come to some sort of agreement or phrasing for that docs page so that NetSparkleUpdater can be seen as available without diminishing WinSparkle in any way, since I believe both libs should stick around. I wanted to come here first to talk with you about it so there's no updating of the docs pages or anything like that without talking to you -- everything is in the open. :)

Potential ideas I had for that first paragraph (with links as appropriate):

* Sparkle is a software update framework for macOS and Windows apps. Implementations of Sparkle on Windows are available in C++ (WInSparkle) and C# (NetSparkleUpdater).
* Sparkle is a software update framework for macOS and Windows (C++, C#) apps.
* Sparkle is a software update framework for macOS and Windows apps. There are multiple implementations of Sparkle available on Windows, including WinSparkle (C++) and NetSparkleUpdater (C#).

The third option I like because it would allow for more implementations to be easily added in the future if those ever come about.

Do you have any thoughts on this or other suggestions?

Thanks!

**Comment by vslavik** [comment]
Nice to see NetSparkleUpdater active!

Personally, I'd just do AppCenter maintainers do what they want on their own without pushing them in any direction (I didn't ask for WinSparkle's inclusion, although I noticed a while back), but that's me, to my own detriment.

I do take some issue with the phrasing that suggests WinSparkle is for C++ and NetSparkleUpdater for C#. WinSparkle is *implemented* in C++ but that is, well, an implementation detail that its user shouldn't give a damn about. The API is intentionally portable C one, easily bindable, with bindings to other languages, and usable from other languages even without bindings — which is in fact the case for C#. Proper .NET binding is coming too.

I would suggest to keep it non-verbose in the way AppCenter docs authors clearly think is appropriate, i.e. just a few words, neutral, to the point:

> Sparkle is a software update framework for [macOS](http://sparkle-project.org/) and Windows ([WinSparkle](https://winsparkle.org/), [NetSparkleUpdater](https://github.com/NetSparkleUpdater/NetSparkle)) apps.

I think this is fairest, it encourages clicking through and making one's own judgement. There even is a bit of a nudge in the right direction: "win" says it is Windows-only (NetSparkleUpdater isn't) and "net" that it is .NET-only (WinSparkle isn't).

**Comment by Deadpikle** [comment]
@vslavik 

I am so, _so_ sorry for neglecting to reply. I apologize -- life is really busy right now, and frankly, I forgot about this. If you're waiting on me in the future, please feel free to ping me again. 😅 

I agree with your assessment about the wording and your phrasing. That way, things stay more open should more Sparkle ports come around for one reason or another. I'm willing to roll with that.

I'm not quite ready to update the actual MS docs yet until I am able to update some more docs for NetSparkleUpdater. Since I have the info I wanted though and there's a public record of our conversation here, I'm willing to close the issue. Would you like this closed, or would you like me to close it when I PR the docs to be updated? Either way, I'll come back here when things are done just so you're in-the-know.

**Comment by vslavik** [comment]
> life is really busy right now

Tell me about that...

The issue is save to close, I think, and appreciate that you kept me in the loop.

**Comment by Deadpikle** [comment]
Hi again,

Just an FYI that I have finally requested that this change be made (https://github.com/MicrosoftDocs/appcenter-docs/pull/1226) now that NetSparkleUpdater 2.0 is out!

Thanks again for working with me on this.
