### ISSUE TITLE
Update only shows downloaded zip file in explorer, does not replace and update application

### ISSUE THREAD

**Issue by patrickkidd** [vslavik/winsparkle#219]
The title says it all. Shouldn't WinSparkle replace the running exe? All it does for me is download the update and show the contents of the zip file in explorer. It leaves the old exe running.

Windows doesn't allow you to replace a running exe, but it does allow you to move it. My suggestion would be to just move the current exe somewhere else then move the downloaded exe in to where the current exe was, then execute the new exe and exit from the old one.

Where would be the best place in the code to add this? Should only be a few lines considering the zip file is already downloaded and the path is known.

**Comment by vslavik** [comment]
WinSparkle expects the update to be in a native form. A ZIP archive with something ill-specified is not that.

I'd be happy to integrate *proper* support for such archives, will well-specified behavior and robust implementation.

> Windows doesn't allow you to replace a running exe, but it does allow you to move it.

That's good to know, it does make things simpler (though certainly not *simple*).

**→ #220**
