### ISSUE TITLE
How to load local AppCast file to win_sparkle_set_appcast_url()

### ISSUE THREAD

**Issue by varmatangoit** [vslavik/winsparkle#222]
how to load a local appcast file.
my application creates the appcast file, so its needed that, the appcast be loaded from local location.

**Comment by vslavik** [comment]
That doesn't make any sense.

Please don't use this *bug* tracker for questions. If you truly need to do something as non-standard as that (I very much doubt that), you have the source code at your disposal - read it, modify as you need.
