### ISSUE TITLE
Without a DSAPub key win_sparkle_set_registry_path() causes crash on 2nd+ launch

### ISSUE THREAD

**Issue by supersv** [vslavik/winsparkle#225]
Again, basic WinSparkle setup without a DSAPub key:

Calling `win_sparkle_set_registry_path()` causes a crash due to an unhandled exception on 2nd+ app launch.

Init code:

```
::win_sparkle_set_appcast_url("https://.../appcast.xml");
::win_sparkle_set_registry_path("Software\\COMPANY\\PRODUCT\\WinSparkle");
::win_sparkle_init();
```

Registry after 2nd+ launch:

![Screen Shot 2020-12-25 at 14 07 42](https://user-images.githubusercontent.com/12841842/103134548-96098600-46ba-11eb-9b74-b6852a6c0e88.png)

I fully understand that this is unintended usage (no DSAPub key), but perhaps something you should be aware of, as without the `win_sparkle_set_registry_path()` call it's just a message in the output log, and not the exception.

![Screen Shot 2020-12-25 at 14 09 46](https://user-images.githubusercontent.com/12841842/103134581-de28a880-46ba-11eb-9c8b-361ce05e54ba.png)

**Comment by supersv** [comment]
Nevermind, the problem was not with the missing DSAPub, but with my "VarFileInfo" / "Translation" - fixing that made the crashes from `DoGetVerInfoField()` go away.

**Comment by vslavik** [comment]
> Nevermind, the problem was not with the missing DSAPub, but with my "VarFileInfo" / "Translation" 

The time to do this basic investigation (i.e. why do I think it is a crash? can I get a backtrace? why do I think it is related to that specific function? why do I think it is related to DSA keys? can I reproduce it in the bundled example app? why not?) is ideally before filing an issue...
