### ISSUE TITLE
Add support for DSA signed updates

### ISSUE THREAD

**Issue by vslavik** [vslavik/winsparkle#23]
You mention in your docs that signing updates is not yet supported, but I didn't see this in the planned features list. So hereby I am requesting this feature.

Background: We are considering using Sparkle for ScummVM ( http://www.scummvm.org) on Mac OS X. It then would make a lot of sense to also use WinSparkle for our Windows port. But I would feel very uncomfortable about installing unsigned updates automatically this way. (Granted, we don't yet provide signatures for our regular downloads either, but this, too, is something that should change).

Hopefully this won't be too difficult to implement. Microsoft seems to provide an API for verifying crypto signatures (including DSA support), according to MSDN ( http://msdn.microsoft.com/en-us/library/aa387761%28v=VS.85%29.aspx)

**Comment by treasurebox** [comment]
Slightly related question: Does WinSparkle support downloading the xml from https:// _but_ only if ssl cert is okay? 
I couldn't find any mention about this about the doc, but either executable signature checking or https xml fetching seems to be a minimum for not opening a backdoor on user's machine.
Thank You for the quick answer, and the awesome work so far!

**Comment by vslavik** [comment]
> related

That word doesn’t mean what you think it means. Please don’t post completely off-topic comments like this.

> Does WinSparkle support downloading the xml from https:// but only if ssl cert is okay? 

You have the code at your disposal, why don’t you verify it yourself and if there’s any issue, submit a patch? 

> for the quick answer

This is a volunteer, community project, please don’t treat it as a commercial offering with support. Instead, *contribute* — even if it’s “only” information or documentation improvements.

**Comment by treasurebox** [comment]
I think it's not off topic at all. The same people who think they need DSA signed updates might just be satisfied with https based xml download.
Anyway, looking into the code, it uses InternetOpenUrl(), which is not very well documented in this regard, but trying it out (see http://stackoverflow.com/questions/29545544/is-internetopenurl-function-on-windows-secure-enough-if-not-how-to-make-it-str/29576201#29576201), it seems that it indeed checks https validity by default. So the answer to my own question is yes.

**Comment by vslavik** [comment]
> I think it's not off topic at all.

This issue is for tracking support for DSA signatures. You ask a question about validation of certificates, which is something that has *zero* overlap with the issue’s subject, technically or thematically. You are off topic *by definition*. By your the-same-people logic, *anything* about WinSparkle would be on-topic in *any* issue...

**Comment by mm-akruse** [comment]
Hi, has there been any determination on this issue? Last activity is about a year and a half ago.

Thanks!

**Comment by vslavik** [comment]
@mm-akruse This is an Open Source project developed by volunteers in their spare time. If you need some functionality, *do* something about it. Your PR would be most welcome. That's what Open Source is about -- sharing, scratching your own itch and giving back. What OSS *isn't* about, though, is bugging developers to address *your* needs or spamming issues with pointless questions (the state of all issues and code is public!). That goes doubly when you're using WinSparkle for commercial gain, as you do.
