### ISSUE TITLE
Qt widgets support

### ISSUE THREAD

**Issue by daschuer** [vslavik/winsparkle#231]
Does the work exists, that uses Qt instead of WxWidgets. This would make styling with Qt Apps more consistent. 

Is there interest to add qt as an optional feature?

**Comment by Youw** [comment]
Once I've developed a Qt desktop application (several yers ago) for Windows and macOS, and I needed a mechanism for updates. At that time such project didn't exist. Brief googling today didn't show any changes in this are.

For my scenario (a desktop application for Windows and macOS) I did the most obvious thing I could think of at the time: make my own small Qt wrapper that would use WinSparkle on Windows and [Sparkle](https://github.com/sparkle-project/Sparkle) on macOS as a "backend" mechanism.

---
I once even though of starting a `qsparkle` project, that would be a functional clone of Sparkle+WinSpakrle (but implemented using native Qt only, maybe with OpenSSL or smth), but as one can imagine - it is one hell of a project and I couldn't find time even to start it.

**Comment by daschuer** [comment]
Interesting. Is that code public available?

I have seen the Wireshark solution that uses also both sparkle clones
https://github.com/wireshark/wireshark/blob/eb5f4eea99593b92298bacecc5c9d885cc13a9ad/ui/software_update.c#L45

**Comment by Youw** [comment]
Unfortunately that project isn't publicly available, but the wireshark approach is pretty much the same as was mine.

**Comment by vslavik** [comment]
I have no intention to duplicate all the GUI code for a non-native framework like Qt. WinSparkle uses native win32 controls, so inconsistency with Qt is because Qt is non-Windows-native...
