### ISSUE TITLE
Using cached release notes

### ISSUE THREAD

**Issue by rtavakko** [vslavik/winsparkle#235]
I've been experiencing an issue that I'm not sure how I can troubleshoot. I'm using WinSparkle 0.7.0 I generate an appcast and an html release notes file using a script and upload them to a server. WinSparkle can read the appcast and shows the correct version for the latest update, but it seems to use cached release notes from the previous version. 

I was looking at this issue:
https://github.com/vslavik/winsparkle/issues/33

And thought maybe this is related to cache settings on the server, but just for the sake of narrowing things down, I have been clearing cache on my server during my testing. Also WinSparkle downloads the correct update and all is well afterwards too. After the update is installed, the library correctly notes that the latest version is being used. 

So it seems that a cached version is being used just for release notes. If release notes are cached, is there a specific naming scheme for the folder? 

I would greatly appreciate any thoughts on how to troubleshoot this and have a test project to share if needed.

**Comment by Lyrha** [comment]
The server is set to never cache the release notes and returns a MISS:
server:
nginx
date:
Mon, 06 Sep 2021 14:26:27 GMT
content-length:
501
connection:
keep-alive
last-modified:
Mon, 06 Sep 2021 14:17:22 GMT
etag:
"1f5-5cb544ebf368f"
accept-ranges:
bytes
x-httpd:
1
cache-control:
private
host-header:
6b7412fb82ca5edfd0917e3957f05d89
x-proxy-cache:
MISS
x-proxy-cache-info:
0 NC:000000 UP:SKIP_CACHE_PRIVATE

I've tried setting the cache-control header this way:

win_sparkle_set_http_header("Cache-Control","no-cache");

Is there a setting or a flag to make sure nothing is cached? It seems this is the case for appcasts and the actual download file.

**Comment by vslavik** [comment]
> The server is set to never cache the release notes and returns a MISS:

I don't know what you mean by "returns a MISS" in the context of HTTP protocol responses (it's not standard terminology or HTTP response) or by "set to never cache" (it's the clients, not server, who caches), but you are mistaken about the server not instructing to cache. In fact, it is doing the exact opposite and explicitly *asks* for caching:
```
cache-control: private
```


If you believe there is a problem in WinSparkle, please read  http://www.chiark.greenend.org.uk/~sgtatham/bugs.html first and *then* collect a proper reproduction steps that a person-that-is-not-you can follow and reproduce the issue. Without that, everything points to this being a misunderstanding of HTTP caching.
