### ISSUE TITLE
Question: How to close and relaunch application when installer runs

### ISSUE THREAD

**Issue by duncangroenewald** [vslavik/winsparkle#242]
Did I miss something here - I was expecting the WinSparkle to automatically close and relaunch the application but it seems it does not do this or did I miss a configuration option somewhere?

If not done by WinSparkle then how should this be done - the windows installer ?  And if so any pointers for information on how that gets done ?

Also - it might be worth updating documentation to explain where and how this should be done to allow installation to complete.

**Comment by vslavik** [comment]
Duplicate of #132.
