### ISSUE TITLE
Error:  The update is improperly signed

### ISSUE THREAD

**Issue by duncangroenewald** [vslavik/winsparkle#243]
Why am I suddenly getting this error and how can I fix this. 

I have tried deleting all the packages and starting again by generating new keys and rebuilding and resigning the installer but all to no avail.

The only think I have done that might have caused a problem was to install netsparkles generate-appcast to try that out .  Is it possible that that has somehow affected how things are being signed or changed the openssl somehow to prevent the WinSparkle sign_updated.bat from working correctly?

**Comment by vslavik** [comment]
> Why am I suddenly getting this error 

Because you made some mistake when signing. You don't provide any details, it's impossible to know where you went wrong.

> how can I fix this.

By signing properly.

Please note this is a bug tracker, not support forum.
