### ISSUE TITLE
Installation instructions need updated

### ISSUE THREAD

**Issue by sean-neeley** [vslavik/winsparkle#255]
The command in the readme does not work:
`git clone git://github.com/vslavik/winsparkle.git`

It should be:
`git clone https://github.com/vslavik/winsparkle.git`

Can you update?

**Comment by vslavik** [comment]
> Can you update?

Why don't you submit a PR?

**Comment by sean-neeley** [comment]
I'm super lazy, but I have done as you have asked.  Thanks.

**Comment by vslavik** [comment]
Merged in [11452ba](https://github.com/vslavik/winsparkle/commit/11452baa5529590031904ae3c4d0c9c11f53d864), thanks!
