### ISSUE TITLE
Wixtoolset for msi update

### ISSUE THREAD

**Issue by dIvYaNshhh** [vslavik/winsparkle#259]
I have gone through many documents and articles but have not been able to find the proper resolution when using the Wix installer(.msi).

In my case, it's downloading the latest version, and after completing the download it asks to install the update but when the MSI installer invokes and closes automatically, nothing happens, and no error I got and there is no latest version updated.

Can anyone help me out and guide me on this?

**Comment by vslavik** [comment]
This is a bug tracker, not discussion forum. And your MSI or WiX issues are unrelated to WinSparkle, so it's unclear why would you even post it here.
