### ISSUE TITLE
sparkle:os seems to be ignored

### ISSUE THREAD

**Issue by Foaly** [vslavik/winsparkle#276]
Hello there!

Consider the following: I have a windows application in version 0.9.0 and the following appcast.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>UpdaterExample Release</title>
    <description>The latest stable release of UpdaterExample.</description>
    <language>en</language>

    <item>
      <title>Version 1.0.0</title>
      <pubDate>Tue, 21 May 2024 14:31:00 +0000</pubDate>
      <enclosure sparkle:os="macos"
                 sparkle:version="1.0.0"
                 url="https://www.link.to.a.dmg"
                 length="2620494"
                 type="application/octet-stream"/>
    </item>
  </channel>
</rss>
```

If I run the update command WinSparkle will download and run the dmg from the macos enclosure url. I would expect is to say no new version available. This seems like a bug to me. Please let me know if I am missing anything.

Thank you for your work and this great library.

**Comment by Foaly** [comment]
I did read around in the code a bit and might have found something.

When loading the appcast file the following code is executed:
https://github.com/vslavik/winsparkle/blob/master/src/appcast.cpp#L371-L386

First all available items are check with `is_suitable_windows_item` (https://github.com/vslavik/winsparkle/blob/master/src/appcast.cpp#L203)

This should fail, as the os string should be macos and not windows.

After this check fails all items are checked again using `is_windows_version_acceptable` (https://github.com/vslavik/winsparkle/blob/master/src/appcast.cpp#L94)

This function for some reason returns true if not minimum version was set. 

I think this might be the reason why the item above passes eventhoug it should clearly. I tried adding a `<sparkle:minimumSystemVersion>` tag to the item and then the problem is gone. I still think this is a bug though and I don't really understand the logic why if no suitable os item is found the version is checked again. Shouldn't the logic be reversed? Only check the version once the os is confirmed to be correct? 

I might be missing some points though, as I only had a quick look at the code, which I am not familiar with and I did no real testing!

**Comment by vslavik** [comment]
I'm not surprised you can't make much sense of the logic; neither can I :(

**Comment by Foaly** [comment]
So what can we do about it? I think maybe the logic has to be rethought.

**Comment by vslavik** [comment]
> So what can we do about it?

Well, certainly not nagging with this sort of non-contributing comment. You can submit a PR (that would be useful) or you can show some patience.

**Comment by i-n-g-o** [comment]
Hello.

I ran into a similar situation. This PR should fix this issue: https://github.com/vslavik/winsparkle/pull/279

**Comment by vslavik** [comment]
> Am I missing anything?

I don't think you are. I couldn't see an easy way to tackle this, so took the opportunity to fix it "properly" — hopefully the changes in PR #283 will make the code easier to follow and more robust in the future.

**Comment by Foaly** [comment]
Thank you very much for taking the time to rework this! 🚀
