### ISSUE TITLE
the winSpakle windows was behind by my application

### ISSUE THREAD

**Issue by brokensword2018** [vslavik/winsparkle#278]
the winSpakle windows was hide by my application while I set Qt::WindowStaysOnTopHint for my application. It was ok. while  I do not set Qt::WindowStaysOnTopHint.

**Comment by brokensword2018** [comment]
sorry for my poor english。
![image](https://github.com/user-attachments/assets/143ee1e9-cd45-479e-b2ca-b0b77b7ae1bc)
winsparkle window is behind my application window. my application is based Qt。 and the window has set Qt::WindowStaysOnTopHint

**Comment by vslavik** [comment]
English is not the issue. But you don't provide any details, don't explain anything, don't provide steps to reproduce, any test code, nothing.

I asked you to read an article that teaches you how to report issues well. It is evident that you didn't read it.

**Comment by brokensword2018** [comment]
reproduce steps:
1、create a window A with Qt::WindowStaysOnTopHint。
2、call win_sparkle_check_update_with_ui （it's already the lastest version）。 the winsparkle will show window B。
the problem is the window B is behind A。

**Comment by vslavik** [comment]
Closing as not reproducible, then. If you want read the article and submit a usable bug report, you'll have to fix whatever it is yourself and submit a patch. I have neither patience nor time for playing a broken record.
