### ISSUE TITLE
Optionally launch web browser

### ISSUE THREAD

**Issue by joshkel** [vslavik/winsparkle#39]
Our updates are hosted on a password-protected web site, and rather than make users enter their username and password into the WinSparkle UI, I'd like to simply launch a web browser to the download page if a new version is detected.

It looks like neither WinSparkle nor Sparkle currently supports this?

Any thoughts on adding such a feature? E.g., if no `<enclosure>` is present and a `<link>` is present, then launch a browser to that link if the user clicks update. I can work on implementing it if you're open to the idea.

**Comment by vslavik** [comment]
> E.g., if no <enclosure> is present and a <link> is present, then launch a browser to that link if the user clicks update

Sounds sensible to me.

**Comment by vslavik** [comment]
> I can work on implementing it if you're open to the idea.

@joshkel Just to be clear: yes, I think it makes sense to add it, and a pull request would very much be appreciated. (I just realized my in-a-hurry reply above was a bit terse.)

**Comment by joshkel** [comment]
@vslavik I understood, and I just submitted a pull request. Thanks!
