### ISSUE TITLE
Orphaned process with win_sparkle_cleanup()

### ISSUE THREAD

**Issue by adipose** [vslavik/winsparkle#42]
If I call win_sparkle_cleanup() before closing my application, an orphaned process stays in memory.  If I don't call it, nothing seems to go wrong, and there is no orphaned process.

Do I really need to call cleanup()?

**Comment by vslavik** [comment]
WinSparkle doesn't launch any processes (except the installer when installing); I have no idea what you might be talking about here.

As you could trivially verify yourself if you look at the code, `win_sparkle_cleanup()`  *shuts down* WinSparkle's thread that would *otherwise* be left running.

Are you sure you aren't jumping to incorrect conclusions as you did in #41? Can you provide any specific *evidence* — anything that would make it actually possible to reproduce/verify/debug this?

**Comment by adipose** [comment]
Jumping to incorrect conclusions?  Probably :)

I called win_sparkle_cleanup() on my Qt process's main widget destroy method.  When I closed my process, my process had disappeared (no window), but it was still running in the process manager.  It never goes away.

If I removed the cleanup() method, the process exited cleanly.  The only conclusion I could come to is that the cleanup() method actually never exits, so my process never completes, either.

**Comment by vslavik** [comment]
Did you observe that behavior in the included sample? If not (and I do not), then it would be indicative of *something* being different in your code — the question is, *what* that is. The preferred conclusion would be "hey, I need to debug this a bit" — could you please use your debugger to find out what's going on inside the cleanup call? Or alternatively provide some sample code that exhibits the wrong behavior?

**Comment by adipose** [comment]
I have not tried your sample, but I do have a reproduction in a small piece of code.

I have more information on the bug, as well.  It occurs the second time you run the application.  In other words, the "DidRunOnce" registry entry must be present, but "CheckForUpdates" must not.  In order to activate the bug, you must ignore the "Software Update" window and close the primary window.  The "Software Update" window will remain.  When you close the primary window, you will see the "About to cleanup" message below.  But even after you close the "Software Update" window (second), the "Cleaned up" message will not appear.  And, the process will still be running with no windows.

main.cpp
```cpp
#include <QApplication>
#include <QtGui>
#include <QtWidgets>
#include "test.h"


int main(int argc, char *argv[]) {
  QApplication app(argc, argv);
  test qmw;
  qmw.show();
  return app.exec();
}
```

test.h
```cpp
#ifndef TEST_H
#define	TEST_H

#include "QtWidgets"
#include "QtGui"
#include <winsparkle.h>

class test  : public QMainWindow
{
	Q_OBJECT

public:
  test() {
    win_sparkle_init(); //sloppy, but good enough to test this bug
  }
  virtual ~test() {
    QMessageBox::information(this, "Before", "About to cleanup");
    win_sparkle_cleanup();
    QMessageBox::information(this, "After", "Cleaned up"); //never happens
  }
private:

};

#endif	/* TEST_H */
```

**Comment by vslavik** [comment]
To clarify this bug report, a crucial piece of information is missing: this happens *if and only if* WinSparkle is asking for permission to check for updates; not, as the above sounds like, when showing the actual updates window.

The above test is not reproducible either, because it is missing crucial WinSparkle initialization of the feed and it errors out immediately.

**Comment by adipose** [comment]
That's strange, in my test case it did not error out.  Thanks for fixing the bug!

**Comment by adipose** [comment]
I was using release 0.4, so perhaps that's why it didn't error out without those settings.

**Comment by vslavik** [comment]
> I was using release 0.4, so perhaps that's why it didn't error out without those settings.

No, this is version-independent — the example above doesn't set up the appcast feed, so no UI (which is where the problem was) was ever shown. I assume you had some resources compiled in, that's all, so I added the info programmatically:
```cxx
win_sparkle_set_appcast_url("http://winsparkle.org/example/appcast.xml");
win_sparkle_set_app_details(L"winsparkle.org", L"WinSparkle Qt Example", L"1.0");
```

**Comment by adipose** [comment]
In the sample above, I had no resource file, and I didn't set the url manually (in my original app, I was using a resource file to set appcast).

It might have errored later (I never saw it do so), but it definitely did pop up the permission dialog.  I'm not sure why it didn't have the same result for you.

My reproduction was deliberately as simple as possible to create the issue, but the appcast url didn't appear necessary to pop up the dialog.  I just ran it again (after setting registry setting correctly), and it still "works" and causes the bug (with 0.4, with master it is ok).
