### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by kkuday** [vslavik/winsparkle#52]
I used win sparkle for update mechanism in my windows application it works fine for me .  I am  facing a problem with  updated exe which pops up and asking for installation, here I want  to  know how to install exe silently without any user interaction.  Is this possible with  current version  of win sparkle ? if it is possible, please let me know in detail   how it works . I  struck at this point for a while.  please do help me .

**Comment by TingPing** [comment]
Duplicate of #21
