### ISSUE TITLE
use winsparkle for my win32 App something wrong! 

### ISSUE THREAD

**Issue by yuqianqiu** [vslavik/winsparkle#56]
when i added winsparkle into my application,an error occurred.
when i called the method  win_sparkle_check_update_with_ui();
Update Error!
An error occurred in retrieving update information:are you connected to the internet?Please try again later.
but  my computer connect to the internet well !
can you help me?  thanks very well !

**Comment by vslavik** [comment]
> can you help me?

Sure. You did something wrong somewhere and you need to fix it, then it will work. You’re welcome.

Sounds useless? But what else do you expect me to tell you if you are so disastrously vague? You’re a *developer*, for crying out loud, diagnosing problems yourself first (which you obviously didn’t even try to) and, failing that, reporting them well, is part of your *job description!* It’s understandable when end users fail at it as miserably as this, but not developers.

Read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html and try again. Don’t forget to actually read the documentation and check the examples first — that’s why they are there. Check your feed’s correctness (and demonstrate that you did). Heck, check your connectivity.

**Comment by TechnikEmpire** [comment]
Believe me I understand your frustration, as someone who answers questions like this regularly on stackoverflow. However, to be fair, you mention nothing about this error in the documentation (that I can find after a few minutes of digging around) and where this error gets thrown in your code, there's no description or reason for the call to the fail state. It's just simply a single fail state for everything, from what I can see.

**Comment by vslavik** [comment]
This error is shown to the *end user*, who is often non-technical and rarely even aware of using WinSparkle. It doesn't make much sense to show more detailed error there, and IIRC Sparkle does the same. More details *are* logged into debug output.

Consider when a failure to process an appcast feed may happen: either it's a connectivity or downtime issue (and in that case this error is spot-on) or the feed's markup is somehow incorrect. In the latter case, it's 100% reproducible on the developer's machine (and should have been caught in even the most basic testing to begin with). The developer can then check the debug output and/or run the code under debugger.

I think it's a justified choice to be vague in this user-facing error. But I'm open to PRs changing this, e.g. to at least say something like "The updates feed is invalid" or something.

**Comment by TechnikEmpire** [comment]
Yeah I wasn't being critical or anything. I ended up successfully integrating WinSparkle into my project within a few minutes of making that comment. It's great, simple and just works. Great project and thanks for publishing it. As you say it was as simple issue with the validation of markup
