### ISSUE TITLE
Can't build wxWidgets with MinGW

### ISSUE THREAD

**Issue by drizt** [vslavik/winsparkle#62]
I got such error:

    [ 76%] Building CXX object 3rdparty/CMakeFiles/wxWidgets.dir/wxWidgets/src/msw/menuitem.cpp.obj
    cd /home/taurus/develop/winsparkle/build/3rdparty && /usr/bin/i686-w64-mingw32-g++   -DNDEBUG -DUNICODE -DWIN32 -DWXBUILDING -D_CRT_SECURE_NO_WARNINGS -D_LIB -D_UNICODE -O3 -DNDEBUG @CMakeFiles/wxWidgets.dir/includes_CXX.rsp   -o CMakeFiles/wxWidgets.dir/wxWidgets/src/msw/menuitem.cpp.obj -c /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/menuitem.cpp
    In file included from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/menuitem.h:198:0,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/menuitem.cpp:28:
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/menuitem.h:125:27: error: 'wxBitmap' does not name a type
         void SetBitmaps(const wxBitmap& WXUNUSED(bmpChecked),
                               ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/menuitem.h:125:35: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
         void SetBitmaps(const wxBitmap& WXUNUSED(bmpChecked),
                                       ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/menuitem.h:126:27: error: 'wxBitmap' does not name a type
                         const wxBitmap& WXUNUSED(bmpUnchecked) = wxNullBitmap) { }
                               ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/menuitem.h:126:62: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
                         const wxBitmap& WXUNUSED(bmpUnchecked) = wxNullBitmap) { }
                                                                  ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/menuitem.h:127:26: error: 'wxBitmap' does not name a type
         void SetBitmap(const wxBitmap& WXUNUSED(bmp),
                              ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/menuitem.h:127:34: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
         void SetBitmap(const wxBitmap& WXUNUSED(bmp),
                                      ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/menuitem.h:129:11: error: 'wxBitmap' does not name a type
         const wxBitmap& GetBitmap() const { return wxNullBitmap; }
               ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/msw/menuitem.h:126:62: error: 'wxNullBitmap' was not declared in this scope
                         const wxBitmap& WXUNUSED(bmpUnchecked) = wxNullBitmap) { }
                                                                  ^
    
    [ 77%] Building CXX object 3rdparty/CMakeFiles/wxWidgets.dir/wxWidgets/src/msw/mslu.cpp.obj
    cd /home/taurus/develop/winsparkle/build/3rdparty && /usr/bin/i686-w64-mingw32-g++   -DNDEBUG -DUNICODE -DWIN32 -DWXBUILDING -D_CRT_SECURE_NO_WARNINGS -D_LIB -D_UNICODE -O3 -DNDEBUG @CMakeFiles/wxWidgets.dir/includes_CXX.rsp   -o CMakeFiles/wxWidgets.dir/wxWidgets/src/msw/mslu.cpp.obj -c /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/mslu.cpp
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/menu.cpp: In function 'bool {anonymous}::IsGreaterThanStdSize(const wxBitmap&)':
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/menu.cpp:292:15: error: invalid use of incomplete type 'const class wxBitmap'
         return bmp.GetWidth() > ::GetSystemMetrics(SM_CXMENUCHECK) ||
                   ^
    In file included from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/event.h:20:0,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/window.h:18,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/menu.h:23,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/menu.cpp:28:
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/gdicmn.h:29:28: error: forward declaration of 'const class wxBitmap'
     class WXDLLIMPEXP_FWD_CORE wxBitmap;
                                ^
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/menu.cpp:293:16: error: invalid use of incomplete type 'const class wxBitmap'
                 bmp.GetHeight() > ::GetSystemMetrics(SM_CYMENUCHECK);
                    ^
    In file included from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/event.h:20:0,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/window.h:18,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/menu.h:23,
                     from /home/taurus/develop/winsparkle/3rdparty/wxWidgets/src/msw/menu.cpp:28:
    /home/taurus/develop/winsparkle/3rdparty/wxWidgets/include/wx/gdicmn.h:29:28: error: forward declaration of 'const class wxBitmap'
     class WXDLLIMPEXP_FWD_CORE wxBitmap;
                                ^
    

I found that if use `#define wxUSE_OWNER_DRAWN 1` in *setup.h* then WinSparkle can be compiled with these errors.

I don't know the best way fix this. So I opened a new issue instead of pull request.

**Comment by vslavik** [comment]
Seems like some missing include in the 3rd party wx code, probably long since fixed there (I really need to update the copy to wx3…). Since the issue doesn’t exist in the official projects, it’s obviously possible to work around it. My guess: try enabling precompiled headers.  In any case, it’s an issue with your unofficial makefiles, not WinSparkle itself → closing.
