### ISSUE TITLE
Hangs static version

### ISSUE THREAD

**Issue by drizt** [vslavik/winsparkle#63]
I compiled static version of WinSparkle. When I started my application with static WinSparkle it hangs on `win_sparkle_check_update_with_ui`. Shared version works fine. I tried to compile WinSparkle with Fedora MinGW and with Windows MinGW. The same problem. I haven't any ideas where problem or how debug this.

**Comment by vslavik** [comment]
Unsupported configuration of the code, using your own build system and possibly code modifications — sorry, but you’ll have to debug that yourself, I really can’t spend any time on this myself. I told you static build is problematic in other issues, I guess this is one such occurrence (could be resources and “main” HMODULE related, but that’s just guessing).
