### ISSUE TITLE
How can I change Icon?

### ISSUE THREAD

**Issue by gunnicus** [vslavik/winsparkle#68]
Hi,

I had a look winsparkle.h, doesn't look like there is an API allows me to change app Icon, please help.

**Comment by vslavik** [comment]
WinSparkle uses application's icon — it's a good choice, it reminds the user what the update is for (particularly when this non-modal window gets hidden accidentally or just not noticed). 

> doesn't look like there is an API allows me to change app Icon, please help.

You know what to do when there isn't an API you need? A pull request. Quality PRs are always welcome.
