### ISSUE TITLE
Request: Add Registry item to control how often to check for updates

### ISSUE THREAD

**Issue by computeronix** [vslavik/winsparkle#69]
Could you have a registry setting enabled to control how often to check for updates?  For instance check every day, week, month, or based on a time of seconds?

**Comment by vslavik** [comment]
Please [RTFM](https://github.com/vslavik/winsparkle/blob/116fe18b9c508f7dbb681ce09ef0f61899fb74c3/include/winsparkle.h#L249) first — it's not that hard. Already there, for a long time.
