### ISSUE TITLE
What assumptions can I make about HTTPS security?

### ISSUE THREAD

**Issue by bdesham** [vslavik/winsparkle#71]
I’d like my application to access my appcast and installers via HTTPS. I have several questions about the security of this approach. (For example, is the domain name on the SSL certificate checked to make sure it matches the domain being accessed? Are there any situations in which an HTTPS error would silently cause the connection to fall back to HTTP? How are invalid or questionable certificates handled?)

I get the impression that WinSparkle delegates all of its downloading activity to standard Windows functions. Is that right? Does WinSparkle deviate from the default settings for anything related to HTTPS?

**Comment by vslavik** [comment]
> Are there any situations in which an HTTPS error would silently cause the connection to fall back to HTTP?

Err, no, of course not, that's not how HTTPS works...

> I get the impression that WinSparkle delegates all of its downloading activity to standard Windows functions. Is that right? Does WinSparkle deviate from the default settings for anything related to HTTPS?

Standard WinInet API is used — as you could [see for yourself](https://github.com/vslavik/winsparkle/blob/master/src/download.cpp).

As for your other questions: you have the source code at your disposal. Try it. Experiment. If you find any issues, report them. But you probably won't, as a quick Google search would tell you: [[1]](http://stackoverflow.com/questions/29545544/is-internetopenurl-function-on-windows-secure-enough-if-not-how-to-make-it-str) or [[2]](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385098(v=vs.85).aspx).
