### ISSUE TITLE
Building WinSparkle-2015.sln on VS2015 Community results in build error: Cannot open Debug/WinSparkle.lib

### ISSUE THREAD

**Issue by ciarancourtney** [vslavik/winsparkle#80]
LNK1104 cannot open file 'C:\Users\ciaran\Workspace\winsparkle\Debug\WinSparkle.lib'

**Comment by vslavik** [comment]
A problem with your computer, file permissions or something, not the project files. Apply some common sense, please. 

If you believe this really is a bug in the solution, provide some *evidence* in the form of either a fix (preferred) or conclusive detailed description of just how is the project causing it.

**Comment by ciarancourtney** [comment]
Built with VS2010 instead, I'm just pointing out that it does not build using VS2015 Community

**Comment by vslavik** [comment]
You’re not pointing out anything like that, you’re misinterpreting some local fluke of yours as having anything to do with a) VS2015 and b) its Community edition. In all likelihood, neither of that is true.
