### ISSUE TITLE
Complete silent mode

### ISSUE THREAD

**Issue by David-Haim** [vslavik/winsparkle#87]
So, after looking at the issues opened for WinSparkle, does it provide complete silent mode? no ui what so ever? I can see that people talked about merging silent mode option, but I did not find any API which is completly UI-less.

**Comment by vslavik** [comment]
> but I did not find any API which is completly UI-less.

You answered your own question. Please don't post *questions* as issues, especially when you're perfectly capable of answering them yourself (you have the source code!) and when *there already are open issues on the subject* (so much for "after looking at the issues"). Your contribution to implement fully silent mode would be most welcome.
