### ISSUE TITLE
New release someday?

### ISSUE THREAD

**Issue by honkmaster** [vslavik/winsparkle#92]
When looking at https://github.com/vslavik/winsparkle/releases, Version 0.4 is the current release. However, it dates back to September 14. Since then there have been many bugfixes. Do you plan to pack a new release sometime soon?

**Comment by vslavik** [comment]
> Do you plan to pack a new release sometime soon?

Yes.

In the meantime, bugging non-issue questions like this do nothing to speed it up (unlike e.g. contributing NuGet support…). Just use the `master` branch — you're a *developer*, for crying out loud, it shouldn't be that hard.

**Comment by honkmaster** [comment]
Dear  @vslavik. 

Thanks for the quick response. I am not crying out loud, just a simple and serious question. I was asking for a releases / git tags as those often mark a stable version of a component. 

You did great work since 0.4 and I just though this should be available to everyone. Using a `master` branch directly is sometimes not convenient and dangerous (as some commits might introduce bugs). Nontheless I am using the master already, and it is not that hard, However, I think there are some people who might prefer the drag-and-drop approach. 

Whwhatsoever ... keep up the good work ... sorry for buzzing around.

**Comment by vslavik** [comment]
>  I am not crying out loud

I think you misunderstood that colloquial expression…

> Using a master branch directly is sometimes not convenient and dangerous

There's no "danger" or quality difference between `master` and some arbitrarily tagged point at it called "release". Here, `master` is always considered production ready (and indeed, I do use it in production).

> However, I think there are some people who might prefer the drag-and-drop approach.

That's what I don't get, then, why are you filling an issue on behalf of some theoretical other people.

Anyway: there will be more releases, soon-ish, but there are some issues to be taken care of first.

**Comment by vslavik** [comment]
FYI: I wanted to put more fixes into it, but Expat's security release forced my hand, so I just released 0.5.
